name: dependencies
on:
  workflow_dispatch: {}
  schedule:
    # "At 06:00 on Wednesday" UTC
    # i.e. 7 am CET or 8 am CEST
    # https://crontab.guru/#0_6_*_*_3
    - cron: 0 6 * * 3

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Update Dependencies
        run: |
          yarn install
          yarn npm-check-updates --upgrade --packageFile package.json
          yarn install
          yarn upgrade
      - name: Create Pull Request
        with:
          committer: GitHub Actions <actions@github.com>
          commit-message: 'chore(deps): update all ðŸš€'
          title: 'chore(deps): update all ðŸš€'
          body: 'Please look at the diff for changes'
          author: GitHub Actions <actions@github.com>
          branch: chore/update-dependencies
          branch-suffix: timestamp
          reviewers: nihalgonsalves
        uses: peter-evans/create-pull-request@v3
